export const Product=[{
    id:1,
    title:'battery',
    price:500,
    image:'./electric/camera.webp',
    type:"electric",
    quantity:1
},
{
    id:2,
    title:'camera',
    price:500,
    image:'./electric/camera2.webp',
    type:"electric",
    quantity:1
},

{
    id:3,
    title:'dryer',
    price:500,
    image:'./electric/hairdryer.webp',
    type:"electric",
    quantity:1
},
{
    id:4,
    title:'iphone',
    price:500,
    image:'./electric/iphone.webp',
    type:"electric",
    quantity:1
},
{
    id:5,
    title:'trimmer',
    price:500,
    image:'./electric/trimmer.webp',
    type:"electric",
    quantity:1
},
{
    id:6,
    title:'tv',
    price:500,
    image:'./electric/tv.webp',
    type:"electric",
    quantity:1
},
{
    id:7,
    title:'veet',
    price:500,
    image:'./electric/veet.webp',
    type:"electric",
    quantity:1
},


{
    id:31,
    title:'bag',
    price:300,
    image:'./fashion/bag.webp',
    type:"fashion",
    quantity:1
},
{
    id:32,
    title:'dress',
    price:300,
    image:'./fashion/dress.webp',
    type:"fashion",
    quantity:1
},
{
    id:23,
    title:'glasses',
    price:300,
    image:'./fashion/glasses.webp',
    type:"fashion",
    quantity:1
},
{
    id:34,
    title:'handBag',
    price:300,
    image:'./fashion/hand bag.webp',
    type:"fashion",
    quantity:1
},
{
    id:35,
    title:'jewellery',
    price:300,
    image:'./fashion/jewellery.webp',
    type:"fashion",
    quantity:1
},
{
    id:36,
    title:'kidsCloth',
    price:300,
    image:'./fashion/kids cloth.webp',
    type:"fashion",
    quantity:1
},
{
    id:37,
    title:'kurta',
    price:300,
    image:'./fashion/kurta.webp',
    type:"fashion",
    quantity:1
},
{
    id:38,
    title:'kurtis',
    price:300,
    image:'./fashion/kutis.webp',
    type:"fashion",
    quantity:1
},
{
    id:93,
    title:'pant',
    price:300,
    image:'./fashion/pant.webp',
    type:"fashion",
    quantity:1
},
{
    id:103,
    title:'saree',
    price:300,
    image:'./fashion/saree.webp',
    type:"fashion",
    quantity:1
},
{
    id:11,
    title:'watch',
    price:300,
    image:'./fashion/watch.webp',
    type:"fashion",
    quantity:1
},
{
    id:12,
    title:'shoe',
    price:300,
    image:'./fashion/shoe.webp',
    type:"fashion",
    quantity:1
},


{
    id:13,
    title:'badminton',
    price:200,
    image:'./toys/badminton.webp',
    type:"toys",
    quantity:1
},
{
    id:23,
    title:'batman',
    price:200,
    image:'./toys/batman.webp',
    type:"toys",
    quantity:1
},
{
    id:33,
    title:'cycle',
    price:200,
    image:'./toys/cycle.webp',
    type:"toys",
    quantity:1
},
{
    id:44,
    title:'guiter band',
    price:200,
    image:'./toys/guiter.webp',
    type:"toys",
    quantity:1
},
{
    id:53,
    title:'traiwill',
    price:200,
    image:'./toys/runway.webp',
    type:"toys",
    quantity:1
},
{
    id:63,
    title:'teddy',
    price:200,
    image:'./toys/teddy.webp',
    type:"toys",
    quantity:1
},
{
    id:73, 
    title:'yoga',
    price:200,
    image:'./toys/yoga.webp',
    type:"toys",
    quantity:1
}

]